{% set name = "aiohttp-client-cache" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiohttp_client_cache-{{ version }}.tar.gz
  sha256: 7307ab8bfefe698a0801ba967a9f56ea9fc689fcfc2f3a21b339eeed0bd4e400

build:
  number: 3

outputs:
  - name: {{ name }}
    build:
      script: python -m pip install . -vv
      noarch: python
    requirements:
      host:
        - python >=3.7
        - pip
        - poetry
      run:
        - python >=3.7
        - aiohttp[speedups] >=3.8
        - aiosqlite >=0.16
        - aioredis >=2.0
        - attrs >=21.2
        - itsdangerous >=1.1
        - python-forge >=18.6
        - url-normalize >=1.4
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - aiohttp_client_cache
        - aiohttp_client_cache.backends

  - name: aiohttp_client_cache
    build:
      noarch: python
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
    test:
      imports:
        - aiohttp_client_cache
        - aiohttp_client_cache.backends

about:
  home: https://github.com/requests-cache/aiohttp-client-cache
  summary: Persistent cache for aiohttp requests
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/requests-cache/aiohttp-client-cache
  doc_url: https://aiohttp-client-cache.readthedocs.io

extra:
  recipe-maintainers:
    - JWCook
    - cheginit
